### ISSUE TITLE
Unparsable bug

### ISSUE THREAD

**Issue by orzel** [pallebone/StrictBlockPAllebone#3]
I guess that's not intended, but in the current file, there is a line with TWO IP addresses. That looks like this:

<pre>
223.255.163.236
; Apr 22 16:03:13
; EvilNormalDetect
2.45.70.126 95.47.151.219 
37.116.25.212
98.110.240.177
</pre>

And it breaks parser.

**Comment by pallebone** [comment]
Hi Orzel,

Apologies this bug was missed. Many thanks for taking the time to report it.

I have corrected the error and ensured the line with the 2 IP's are now on separate lines within the file.

Apologies again, this should now be fixed :)

Please let me know if you have any further issues.

Kind regards
Peter

**Comment by pallebone** [comment]
Fix commited.

**Comment by pallebone** [comment]
Hi,

Im closing the issue as there was no further comment and I believe this now be fixed. 

Please reopen if you have further issues :)

Many thanks, kind regards,
Pete

**Comment by orzel** [comment]
Nope, it's perfect, thanks for fixing it !
